[colortheme]
background = [0x26, 0x26, 0x28]
command-bar = [0x20, 0x28, 0x20]
cmdbar-prompt = [0x60, 0x60, 0x60]
cmdbar-cmdexist = [0x40, 0xff, 0x40]
cmdbar-cmdunexist = [0xff, 0x40, 0x40]

[command]
new-window = "n"
quit = "q"
abcdefg = "abcd"
fdsafdsa = "fdsa"
